package:
    name: pairix
    version: "0.1.3"

source:
    git_rev: 0.1.3
    git_url: https://github.com/4dn-dcic/pairix.git

build:
    number: 0

requirements:
    build:
    run:

about:
    home: https://github.com/4dn-dcic/pairix
    license: MIT
